Annotations getters setters
kbuntrock/openapi-maven-plugin pull request #147
Opened 2024-07-24 12:09 UTC by gerhardj

2024-07-28 13:20 UTC, kbuntrock requested changes
Looks pretty nice. Just requested a few minor ajustements.

So sorry for the long delay. Sometimes time just flies by too fast!

Once it's merged I'll do the next release shortly after.

2024-07-28 13:20 UTC, kbuntrock commented on openapi-maven-plugin/src/main/java/io/github/kbuntrock/yaml/model/Schema.java
> +//							final JsonProperty jsonPropertyField = field.getAnnotation(JsonProperty.class);
Commented line to remove

2024-07-28 13:20 UTC, kbuntrock commented on openapi-maven-plugin/src/main/java/io/github/kbuntrock/yaml/model/Schema.java
> +                                          method.getName().equalsIgnoreCase(field.getName())
Could you split lambda with two dedicated functions? 
- One for getters (get + is), checking the return type (already done) + the fact that the parameter count should be equal to zero (not done).
- One for setters, with the parameter count equal to one (already done), type equality (already done) and return type equal to void (not done)

2024-07-28 13:20 UTC, kbuntrock commented on openapi-maven-plugin/src/main/java/io/github/kbuntrock/yaml/model/Schema.java
> +//		final Size size = field.getAnnotation(Size.class);
Commented line to remove

2024-07-29 09:10 UTC, gerhardj-b commented
Many thanks for your review. The requested changes should be done now.

2024-07-29 21:15 UTC, kbuntrock approved these changes
Nice, thank you for your contribution ❤

2024-07-29 21:15 UTC, merged